DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `id` int NOT NULL,
  `name` varchar(1000) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `role` VALUES 
(0,'ADMIN','ADMIN_ROLE'),
(1,'STAFF','STAFF_ROLE'),
(2,'COMPANY_MANAGER','COMPANY_MANAGER_ROLE'),
(3,'COMPANY_EMPLOYEE','COMPANY_EMPLOYEE_ROLE'),
(4,'ATTENDANT','ATTENDANT_ROLE');
