DELETE FROM `role`;

INSERT INTO `role`
VALUES (0, 'ADMIN', 'ADMIN_ROLE'),
       (1, 'COMPANY_MANAGER', 'COMPANY_MANAGER_ROLE'),
       (2, 'COMPANY_EMPLOYEE', 'COMPANY_EMPLOYEE_ROLE'),
       (3, 'ATTENDANT', 'ATTENDANT_ROLE');
