DELETE FROM `residence`;
INSERT INTO `residence` (`id`, `name`)
VALUES (0, 'Đà Nẵng\r'),
       (1, 'Sóc Trăng\r'),
       (2, 'Bình Phước\r'),
       (3, 'Điện Biên\r'),
       (4, 'Ninh Thuận\r'),
       (5, 'Ninh Bình\r'),
       (6, 'Long An\r'),
       (7, 'Đồng Nai\r'),
       (8, 'Vĩnh Long\r'),
       (9, 'Hòa Bình\r'),
       (10, 'Bắc Ninh\r'),
       (11, 'Bình Định\r'),
       (12, 'TP Hồ Chí Minh\r'),
       (13, 'Bạc Liêu\r'),
       (14, 'Đắk Lắk\r'),
       (15, 'Đắk Nông\r'),
       (16, 'Hà Giang\r'),
       (17, 'Bình Dương\r'),
       (18, 'Thái Bình\r'),
       (19, 'An Giang\r'),
       (20, 'Cao Bằng\r'),
       (21, 'Bà Rịa – Vũng Tàu\r'),
       (22, 'Thừa Thiên Huế\r'),
       (23, 'Phú Yên\r'),
       (24, 'Hải Dương\r'),
       (25, 'Bình Thuận\r'),
       (26, 'Tuyên Quang\r'),
       (27, 'Quảng Bình\r'),
       (28, 'Đồng Tháp\r'),
       (29, 'Quảng Nam\r'),
       (30, 'Hải Phòng\r'),
       (31, 'Trà Vinh\r'),
       (32, 'Khánh Hòa\r'),
       (33, 'Tây Ninh\r'),
       (34, 'Yên Bái\r'),
       (35, 'Tiền Giang\r'),
       (36, 'Sơn La\r'),
       (37, 'Hà Nội\r'),
       (38, 'Lào Cai\r'),
       (39, 'Cà Mau\r'),
       (40, 'Quảng Ngãi\r'),
       (41, 'Cần Thơ\r'),
       (42, 'Bến Tre\r'),
       (43, 'Vĩnh Phúc\r'),
       (44, 'Kiên Giang\r'),
       (45, 'Quảng Trị\r'),
       (46, 'Nghệ An\r'),
       (47, 'Lai Châu\r'),
       (48, 'Gia Lai\r'),
       (49, 'Lâm Đồng\r'),
       (50, 'Lạng Sơn\r'),
       (51, 'Phú Thọ\r'),
       (52, 'Hưng Yên\r'),
       (53, 'Kon Tum\r'),
       (54, 'Nam Định\r'),
       (55, 'Hà Tĩnh\r'),
       (56, 'Hà Nam\r'),
       (57, 'Bắc Giang\r'),
       (58, 'Bắc Kạn\r'),
       (59, 'Thái Nguyên\r'),
       (60, 'Hậu Giang\r'),
       (61, 'Thanh Hóa\r'),
       (62, 'International\r'),
       (63, 'Quảng Ninh');


