DELETE FROM `country`;

INSERT INTO `country` (`id`, `name`)
VALUES (1, 'Antigua and Barbuda'),
       (2, 'Burundi'),
       (3, 'Others'),
       (4, 'Barbados'),
       (5, 'Palau'),
       (6, 'Mauritius'),
       (7, 'Timor-Leste'),
       (8, 'Tanzania'),
       (9, 'Lebanon'),
       (10, 'Mozambique'),
       (11, 'Tunisia'),
       (12, 'Belgium'),
       (13, 'Uganda'),
       (14, 'Marshall Islands'),
       (15, 'Laos'),
       (16, 'Côte d\'Ivoire'),
       (17, 'Guinea'),
       (18, 'Madagascar'),
       (19, 'Myanmar'),
       (20, 'Latvia'),
       (21, 'Bahamas'),
       (22, 'Romania'),
       (23, 'Tajikistan'),
       (24, 'Luxembourg'),
       (25, 'Liechtenstein'),
       (26, 'Equatorial Guinea'),
       (27, 'Moldova'),
       (28, 'Congo'),
       (29, 'Monaco'),
       (30, 'Bhutan'),
       (31, 'Bangladesh'),
       (32, 'South Africa'),
       (33, 'Belarus'),
       (34, 'Portugal'),
       (35, 'Estonia'),
       (36, 'New Zealand'),
       (37, 'Uzbekistan'),
       (38, 'Seychelles'),
       (39, 'Benin'),
       (40, 'Solomon Islands'),
       (41, 'Guinea-Bissau'),
       (42, 'Netherlands'),
       (43, 'Dominica'),
       (44, 'Brazil'),
       (45, 'Peru'),
       (46, 'Ecuador'),
       (47, 'Bolivia'),
       (48, 'North Korea'),
       (49, 'Dominican Republic'),
       (50, 'Cyprus'),
       (51, 'Malta'),
       (52, 'Guyana'),
       (53, 'Sierra Leone'),
       (54, 'Angola'),
       (55, 'Luxembourg'),
       (56, 'Afghanistan'),
       (57, 'Samoa'),
       (58, 'Oman'),
       (59, 'Yemen'),
       (60, 'Vietnam'),
       (61, 'Micronesia'),
       (62, 'Algeria'),
       (63, 'Haiti'),
       (64, 'Tuvalu'),
       (65, 'Belize'),
       (66, 'United Kingdom'),
       (67, 'Cameroon'),
       (68, 'Croatia'),
       (69, 'Suriname'),
       (70, 'Russia'),
       (71, 'Denmark'),
       (72, 'Kiribati'),
       (73, 'Nauru'),
       (74, 'Poland'),
       (75, 'Mongolia'),
       (76, 'Gambia'),
       (77, 'Nepal'),
       (78, 'Japan'),
       (79, 'Cambodia'),
       (80, 'Montenegro'),
       (81, 'Armenia'),
       (82, 'Slovakia'),
       (83, 'Sweden'),
       (84, 'Egypt'),
       (85, 'Eswatini'),
       (86, 'Saint Kitts & Nevis'),
       (87, 'Holy See'),
       (88, 'India'),
       (89, 'DR Congo'),
       (90, 'Sudan'),
       (91, 'Cuba'),
       (92, 'Singapore'),
       (93, 'Israel'),
       (94, 'Costa Rica'),
       (95, 'Saudi Arabia'),
       (96, 'Togo'),
       (97, 'Bahrain'),
       (98, 'Rwanda'),
       (99, 'Zambia'),
       (100, 'Canada'),
       (101, 'Guatemala'),
       (102, 'Serbia'),
       (103, 'Jamaica'),
       (104, 'United States'),
       (105, 'Indonesia'),
       (106, 'Ethiopia'),
       (107, 'Sao Tome & Principe'),
       (108, 'Djibouti'),
       (109, 'Thailand'),
       (110, 'Lithuania'),
       (111, 'Central African Republic'),
       (112, 'Namibia'),
       (113, 'Tonga'),
       (114, 'Turkmenistan'),
       (115, 'Nigeria'),
       (116, 'Paraguay'),
       (117, 'Honduras'),
       (118, 'Lesotho'),
       (119, 'Maldives'),
       (120, 'Liberia'),
       (121, 'Nicaragua'),
       (122, 'Mauritania'),
       (123, 'Eritrea'),
       (124, 'France'),
       (125, 'Andorra'),
       (126, 'Ukraine'),
       (127, 'Iceland'),
       (128, 'Somalia'),
       (129, 'Italy'),
       (130, 'Czech Republic (Czechia)'),
       (131, 'Slovenia'),
       (132, 'Comoros'),
       (133, 'Libya'),
       (134, 'Georgia'),
       (135, 'Pakistan'),
       (136, 'Finland'),
       (137, 'Fiji'),
       (138, 'Bulgaria'),
       (139, 'Niger'),
       (140, 'Burkina Faso'),
       (141, 'Vanuatu'),
       (142, 'Philippines'),
       (143, 'Norway'),
       (144, 'Micronesia'),
       (145, 'Trinidad and Tobago'),
       (146, 'St. Vincent & Grenadines'),
       (147, 'United Arab Emirates'),
       (148, 'Iran'),
       (149, 'Malaysia'),
       (150, 'Chile'),
       (151, 'Malawi'),
       (152, 'Cabo Verde'),
       (153, 'Venezuela'),
       (154, 'Mali'),
       (155, 'Zimbabwe'),
       (156, 'Greece'),
       (157, 'Bosnia and Herzegovina'),
       (158, 'Papua New Guinea'),
       (159, 'South Sudan'),
       (160, 'Senegal'),
       (161, 'Spain'),
       (162, 'Mexico'),
       (163, 'Vanuatu'),
       (164, 'Grenada'),
       (165, 'China'),
       (166, 'Cabo Verde'),
       (167, 'Qatar'),
       (168, 'Uruguay'),
       (169, 'Iraq'),
       (170, 'San Marino'),
       (171, 'Turkey'),
       (172, 'Switzerland'),
       (173, 'Kenya'),
       (174, 'Australia'),
       (175, 'Ghana'),
       (176, 'State of Palestine'),
       (177, 'Sri Lanka'),
       (178, 'Kazakhstan'),
       (179, 'Morocco'),
       (180, 'Argentina'),
       (181, 'Jordan'),
       (182, 'Gabon'),
       (183, 'South Korea'),
       (184, 'Panama'),
       (185, 'Hungary'),
       (186, 'Colombia'),
       (187, 'El Salvador'),
       (188, 'Brunei'),
       (189, 'Germany'),
       (190, 'Albania'),
       (191, 'North Macedonia'),
       (192, 'Azerbaijan'),
       (193, 'Saint Lucia'),
       (194, 'Botswana'),
       (195, 'Kuwait'),
       (196, 'Ireland'),
       (197, 'Kyrgyzstan'),
       (198, 'Austria'),
       (199, 'Chad'),
       (200, 'Syria');