DELETE FROM `sub_category`;

INSERT INTO `sub_category`
VALUES (0, 'Geology/Mineral', 0),
       (1, 'Agriculture/Forestry', 0),
       (2, 'Oil/Gas', 0),
       (3, 'High Technology', 0),
       (4, 'Industrial Products', 0),
       (5, 'Auto/Automotive', 0),
       (6, 'Textiles/Garments/Footwear', 0),
       (7, 'Pharmaceutical/Biotech', 0),
       (8, 'Other', 1),
       (9, 'Temporary/Contract', 1),
       (10, 'Overseas jobs', 1),
       (11, 'Expatriate Jobs in Vietnam', 1),
       (12, 'Entry level', 1),
       (13, 'Executive management', 1),
       (14, 'Sales', 2),
       (15, 'Customer service', 2),
       (16, 'Marketing', 2),
       (17, 'Sales Technical', 2),
       (18, 'Household', 3),
       (19, 'Luxury Goods', 3),
       (20, 'FMCG', 3),
       (21, 'Food & Beverage', 3),
       (22, 'Fashion/Lifestyle', 3),
       (23, 'Retail/Wholesale', 3),
       (24, 'Pharmaceutical representatives', 4),
       (25, 'Pharmacist', 4),
       (26, 'Healthcare/Medical Care', 4),
       (27, 'Doctor', 4),
       (28, 'Real Estate', 5),
       (29, 'Architecture/Interior Design', 5),
       (30, 'Civil/Construction', 5),
       (31, 'Warehouse', 6),
       (32, 'Marine', 6),
       (33, 'Freight/Logistics', 6),
       (34, 'IT-Hardware/Networking', 7),
       (35, 'IT-Software', 7),
       (36, 'QA/QC', 8),
       (37, 'Maintenance', 8),
       (38, 'Merchandising/Purchasing/Supply chain', 8),
       (39, 'Planning/Projects', 8),
       (40, 'HSE', 8),
       (41, 'Production/Process', 8),
       (42, 'Export/Import', 8),
       (43, 'Restaurant/Hotel', 9),
       (44, 'Airlines/Tourism', 9),
       (45, 'Legal/Contracts', 10),
       (46, 'Interpreter/Translator', 10),
       (47, 'Human Resources', 10),
       (48, 'Administrative/Clerical', 10),
       (49, 'Accounting', 10),
       (50, 'Banking', 11),
       (51, 'Securities/Trading', 11),
       (52, 'Auditing', 11),
       (53, 'Insurance', 11),
       (54, 'Financial/Investment', 11),
       (55, 'Consulting', 12),
       (56, 'Education/Training', 12),
       (57, 'NGO/Non-profit', 12),
       (58, 'Printing', 13),
       (59, 'Internet/Media', 13),
       (60, 'Advertising/Promotion/PR', 13),
       (61, 'TV/Media/Newspaper', 13),
       (62, 'Telecommunications', 13),
       (63, 'Arts/Design', 13),
       (64, 'Electrical/Electronics', 14),
       (65, 'Mechanical', 14),
       (66, 'HVAC', 14),
       (67, 'Environment/Waste Services', 14),
       (68, 'Chemical/Biochemical', 14);
