name: CI

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    env:
    ## Sets environment variable
      DATASOURCE_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
      DATASOURCE_URL: ${{secrets.DATASOURCE_URL}}
      DATASOURCE_PORT: ${{secrets.DATASOURCE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATASOURCE_USERNAME: ${{secrets.DATASOURCE_USERNAME}}
      DB_DATABASE: ${{secrets.DATABASE_NAME}}
      DB_USER: ${{secrets.DATASOURCE_USERNAME}}
      DB_PASSWORD: ${{secrets.DATASOURCE_PASSWORD}}
    name: Deploy
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
             cd DDL/
             for filename in $(ls -1 * | sort -n); do
              if [[ $filename != "00."* ]]; then
               cat $filename >> schema.sql
              fi
             done
             mysql -h $DATASOURCE_URL -P $DATASOURCE_PORT -u $DATASOURCE_USERNAME -p$DATASOURCE_PASSWORD < schema.sql
             rm schema.sql

             cd ../DML/
             for filename in $(ls -1 * | sort -n); do
              cat $filename >> schema.sql;
             done

             mysql -h $DATASOURCE_URL -P $DATASOURCE_PORT -u $DATASOURCE_USERNAME -p$DATASOURCE_PASSWORD < schema.sql
             rm schema.sql
